name = "grapple-scores"
main = "index.js"
compatibility_date = "2026-07-01"

# Created with: npx wrangler kv namespace create SCORES
[[kv_namespaces]]
binding = "SCORES"
id = "73935e64fa9e4f048d02fc972345e1fa"
